# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 16:33
from __future__ import unicode_literals

from django.db import migrations


def create_super_user_and_group(apps, schema_editor):
    from django.contrib.auth.models import User, Group
    User.objects.create_superuser('admin', 'admin@landloads.com', 'landlady')
    Group(name='landlord').save()
    Group(name='tenant').save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_super_user_and_group),
    ]
